image: node

stages:
  - build
  - deploy

primeiro build:
  stage: build
  script:
    - cd pipe-migration
    - npm install
    - npm run build

primeiro deploy:
  stage: deploy
  enviroment: staging