name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Build Docker image
      run: |
        docker build -t my-python-app .

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag my-python-app "${{ secrets.DOCKER_USERNAME }}/my-python-app:latest"
        docker push "${{ secrets.DOCKER_USERNAME }}/my-python-app:latest"
